### ISSUE TITLE
Meta-issue: optimize isAttacking function for each piece

### ISSUE THREAD

**Issue by Diwakar-Gupta** [Diwakar-Gupta/Chess#15]
When running the current `isAttacking` function for any Piece it calls `isAttacking` function of class `ChessPiece` which can be optimized for each piece.

- [x] Pawn `isAttacking` function optimization #11 
- [ ] Bishop `isAttacking` function optimization
- [ ] Knight `isAttacking` function optimization
- [ ] Rook `isAttacking` function optimization
- [ ] Queen `isAttacking` function optimization
- [ ] King `isAttacking` function optimization
